---
dependency:
  name: galaxy

driver:
  name: default

platforms:
  - name: localhost

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..
  inventory:
    hosts:
      all:
        hosts:
          localhost:
            ansible_connection: local
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
    destroy: destroy.yml

scenario:
  test_sequence:
    - destroy
    - syntax
    - prepare
    - converge
    - idempotence
    - verify
    - destroy

verifier:
  name: ansible
